
INSERT INTO PIDTEST.RESOURCEP (RESOURCE_ID, RESOURCE_NAME, PRESOURCE_ID, RESOURCE_TYPE, NEW_USER, NEW_DATE, UPD_USER, UPD_DATE) VALUES
('TestID3', 'TestName3', 'RES7650', 'content', 'admin@puma.com',CURRENT TIMESTAMP - CURRENT TIMEZONE,'admin@puma.com', CURRENT TIMESTAMP - CURRENT TIMEZONE);
