package com.example.constants;

public interface StringConstants {

	String LEADERSHIP_TOUCH = "LeaderShip Touch";
	String COMMUNICATION = "Communication";
	String TIMELY_RECOGNITION = "Timely Recognition";
	String LEARNING = "Learning";
	String FEEDFORWARD = "Feed Forward";
	String HR_RESPONSIVENESS = "HR Responsiveness";
	String RANDOM_CODE_STRING = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
	String PASSWORD_ENCODING_STRING = "3982";
	String NEW_PASSWORD = "Password1$";
	String CONFORMATION_MSG = "All the employees have not submitted the feedback";
	String CONFORMATION = "Are you Sure?";
	String MONTH = "Month";
	String ERROR_IMG = "srry.png";
	String ERROR_MSG = "<center>You have already submitted this form<center>";
	String STYLE_TITLE_PANEL = "titlepanel";
	String HUNDRED_PERCENT="100%";
	String FORTY_PIXEL="70px";
	String STYLE_TEXT = "textStyle";
	String IMAGE_B1="B1.png";
	String TITLE_WHATSUP_BOARD="<center>WHAT'S UP...??? BOARD SURVEY<center>";
	String FEEDBACK_SUCCESS="Feedback was captured succesfully";
	String SATISFIED="Satisfied";
	String IMAGE_BAD="bad.png";
    String AREA="Area";
    String DESCRIPTION="Description";
    String REASON="Reason";
    String FEEDBACK="Feedback";
    String NAME="Name";
    String EMPLOYEEID="EmployeeID";
    String PROJECT="Project";
    String USER="user";
    String NINE_HUNDRED_PX="900px";
    String PROGRESS_BAR_MSG="% completed,Number of employees left: ";
    String STYLE_SLIDER_BAR="SliderBar";
    String GENERATE_REPORT="Generate Report";
    String EMPLOYEE_NAME="Employee Name";
    String QUALITY_NAME="Quality Name";
    String IS_SATISFIED="Satisfied or Not Satisfied";
    String COMMENTS="Comments";
	String YES = "YES";
	String NO = "NO";
	String ENTER_EMAIL = "Enter Emails";
	String PROP_SASISFIED = "SatisfactoryPercentage";
	String NOT_SATISFACTORY = "Not Satisfactory";
	String SATISFACTORY = " Satisfactory";
	String NOT_SATISFIED = "Not Satisfied";
	String SQL_DRIVER = "com.mysql.jdbc.Driver";
	String SQL_URL = "jdbc:mysql://localhost/Watsup_board";
	String CONFIG_FILENAME = "config.properties";
	String SQL_USERNAME = "root";
	String SQL_PASSWORD = "root";
	String UNSATISFIED_IMAGE = "sad.png";
	String SATISFIED_IMAGE = "bad.png";
	String A = "a";
	String B = "b";
	Object ADMIN = "admin";

}
